name: PullRequest

on:
  pull_request:
    types: [opened]

jobs:
  install_husky:
    runs-on: ubuntu-latest
    steps:
      - name: install commitlint
        run: npm install
      - name: run commit lint
        run: run commitlint --edit $1 --verbose
  run_composer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.3, 7.4 ,8.x ]
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: ${{ matrix.php-version }}
      - uses: actions/checkout@v2
      - name: composer install
        run: composer install
      - name: execute php testes
        run: ./vendor/bin/phpunit --no-configuration tests

