name: PullRequest
on:
  pull_request:
    types: [opened]
jobs:
  allow_pull_request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.3, 7.4 ,8.x ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: get commit message
        run: |
           echo "::`echo $(git log --format=%B -n 2 ${{ github.event.after }})`::"
      - name: show commit message
        run: echo $commitmsg
      - name: show commit message 2
        run: echo github.event.head_commit.message

      - name: npm install
        run: npm install
      - name: execute commitlint
        run: git log -2 --pretty=format:"%s" | npx commitlint --verbose
      - name: git log
        run: git log -5 --pretty=format:"%h | %s"
      - name: composer install
        run: composer install
      - name: execute php testes
        run: ./vendor/bin/phpunit --no-configuration tests

